// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qgdlrplbtgvkhjelqtio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFnZGxycGxidGd2a2hqZWxxdGlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MTQ1NzEsImV4cCI6MjA2OTk5MDU3MX0.hR2InJyYSl3-sCThjGjAj1o3kaKeoUjOUv-66X4rKSM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});